# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'HelloCrypto' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for HelloCrypto
  pod "Alamofire"
  pod "SwiftChart", :inhibit_warnings => true
  
end
